#!/usr/bin/env bash
set -euo pipefail

# Advisory candidate scan for agent-generated-code smells.
# This script is NOT proof, NOT a deletion authority, and NOT a CI gate unless a repo deliberately adopts it.
# Prefer project-specific checks over this generic scan.

usage() {
  cat <<'EOF'
Usage: agent_hygiene_scan.sh [--profile all|fallback|product|types|stale] [--include PATH]... [--exclude GLOB]...

Profiles:
  fallback  Candidate swallowed-error/default-success patterns.
  product   Candidate internal/process leakage in user-facing paths. Use --include for best results.
  types     Candidate weak type/schema shortcuts. Does not flag plain 'unknown' by default.
  stale     Candidate stale markers, placeholders, and agent/process comments.
  all       Run all profiles.

Examples:
  agent_hygiene_scan.sh --profile fallback --include src
  agent_hygiene_scan.sh --profile product --include app --include emails --include exports

Matches are review prompts. They require human/agent judgment and repo-specific context.
EOF
}

PROFILE="all"
declare -a INCLUDES=()
declare -a DEFAULT_EXCLUDE_DIRS=(
  'node_modules'
  '.git'
  'dist'
  'build'
  'coverage'
  '.next'
  '.venv'
  'venv'
  '__pycache__'
)
declare -a USER_EXCLUDES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      if [[ $# -lt 2 || -z "$2" ]]; then
        echo "Missing value for --profile" >&2
        usage >&2
        exit 2
      fi
      PROFILE="$2"
      shift 2
      ;;
    --include)
      if [[ $# -lt 2 || -z "$2" ]]; then
        echo "Missing value for --include" >&2
        usage >&2
        exit 2
      fi
      INCLUDES+=("$2")
      shift 2
      ;;
    --exclude)
      if [[ $# -lt 2 || -z "$2" ]]; then
        echo "Missing value for --exclude" >&2
        usage >&2
        exit 2
      fi
      USER_EXCLUDES+=("$2")
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v rg >/dev/null 2>&1; then
  echo "agent_hygiene_scan: ripgrep (rg) is required." >&2
  exit 127
fi

case "$PROFILE" in
  all|fallback|product|types|stale) ;;
  *)
    echo "Unknown profile: $PROFILE" >&2
    usage >&2
    exit 2
    ;;
esac

if [[ ${#INCLUDES[@]} -eq 0 ]]; then
  INCLUDES=(.)
fi

rg_base() {
  local pattern="$1"
  shift || true
  local args=(-n --hidden --no-heading --color never)
  args+=("$@")
  for ex in "${DEFAULT_EXCLUDE_DIRS[@]}"; do
    args+=(--glob "!${ex}/**")
    args+=(--glob "!**/${ex}/**")
  done
  for ex in "${USER_EXCLUDES[@]}"; do
    args+=(--glob "!${ex}")
    if [[ "$ex" != */* ]]; then
      args+=(--glob "!**/${ex}")
    fi
  done
  local rg_status
  if rg "${args[@]}" "$pattern" -- "${INCLUDES[@]}"; then
    return 0
  else
    rg_status=$?
  fi

  if [[ $rg_status -eq 1 ]]; then
    return 0
  fi
  return "$rg_status"
}

section() {
  echo
  echo "== $1 =="
}

run_fallback() {
  section "Fallback/default-success candidates"
  rg_base 'catch\s*\([^)]*\)\s*\{|catch\s*\{|except\b|rescue\b|return\s+(\[\]|\{\}|(null|undefined|false|true)\b)|pass\s*(#.*)?$|best[- ]effort|fallback|degraded mode|swallow(ed)? error' \
    --glob '*.{js,jsx,ts,tsx,py,rb,go,java,cs,rs,php}'
}

run_product() {
  section "Product-surface leakage candidates"
  echo "Tip: run with --include on user-facing routes/templates/emails/exports to reduce noise."
  rg_base '\b(agent workflow|chain of thought|reasoning trace|implementation detail|internal state|debug trace|mock data|placeholder|temporary|fallback rationale|developer note|TODO)\b' \
    --glob '*.{js,jsx,ts,tsx,py,rb,go,java,cs,md,mdx,html,css,json,yml,yaml}'
}

run_types() {
  section "Weak type/schema shortcut candidates"
  rg_base '\bany\b|Record<string,\s*any>|as\s+any|@ts-ignore|@ts-expect-error|type:\s*ignore|cast\(|TODO\s*:?\s*types?' \
    --glob '*.{js,jsx,ts,tsx,py}'
}

run_stale() {
  section "Stale marker / slop candidates"
  rg_base '\b(TODO|FIXME|HACK|XXX|TEMP|temporary|placeholder|stub|scaffold|demo-only|AI-generated|generated by agent|remove later|for now)\b' \
    --glob '*.{js,jsx,ts,tsx,py,rb,go,java,cs,rs,php,md,mdx,json,yml,yaml}'
}

echo "agent_hygiene_scan: advisory candidate scan only; matches are not proof."
echo "profile=$PROFILE includes=${INCLUDES[*]}"

if [[ "$PROFILE" == "all" || "$PROFILE" == "fallback" ]]; then run_fallback; fi
if [[ "$PROFILE" == "all" || "$PROFILE" == "product" ]]; then run_product; fi
if [[ "$PROFILE" == "all" || "$PROFILE" == "types" ]]; then run_types; fi
if [[ "$PROFILE" == "all" || "$PROFILE" == "stale" ]]; then run_stale; fi

exit 0
